# Shell variables
# Generated by 'wal'
wallpaper='/home/aaron/Pictures/Themes/HEROSCREEN-BACKGROUND300724 (4).png'

# Special
background='#191615'
foreground='#e8dec7'
cursor='#e8dec7'

# Colors
color0='#191615'
color1='#3F8FA1'
color2='#458495'
color3='#649EA4'
color4='#B3B39B'
color5='#CAB998'
color6='#CDC8AD'
color7='#e8dec7'
color8='#a29b8b'
color9='#3F8FA1'
color10='#458495'
color11='#649EA4'
color12='#B3B39B'
color13='#CAB998'
color14='#CDC8AD'
color15='#e8dec7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
