# Shell variables
# Generated by 'wal'
wallpaper='/home/aaron/Pictures/Themes/floating-island-sunset-wallpaper.png'

# Special
background='#08061B'
foreground='#f0c8a3'
cursor='#f0c8a3'

# Colors
color0='#08061B'
color1='#6E3A49'
color2='#254F5D'
color3='#604E57'
color4='#9F3B41'
color5='#9F4A4E'
color6='#E15D4C'
color7='#f0c8a3'
color8='#a88c72'
color9='#6E3A49'
color10='#254F5D'
color11='#604E57'
color12='#9F3B41'
color13='#9F4A4E'
color14='#E15D4C'
color15='#f0c8a3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
