#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## launch waybar with alt config

CONFIG="/home/aaron/.config/waybar/config"
STYLE="/home/aaron/.config/waybar/style.css"

if [[ ! `pidof waybar` ]]; then
	waybar --bar main-bar --log-level error --config ${CONFIG} --style ${STYLE}
fi

# ags
