#!/usr/bin/env bash
# Find the PID of the waybar process
WAYBAR_PID=$(pgrep waybar)
SWAYNC_PID=$(pgrep swaync-client)

# If waybar is running, kill it
if [ -n "$WAYBAR_PID" ]; then
    kill "$WAYBAR_PID"
fi

#If swaync is running, kill it
if [ -n "$SWAYNC_PID" ]; then
    kill "$SWAYNC_PID"
fi

nohup $HOME/.config/varix/labwc/scripts/statusbar &>/dev/null &

swaync-client --reload-config
swaync-client --reload-css

labwc -r &

$HOME/.config/varix/theming/theme.sh --refresh &

$HOME/.config/varix/scripts/gtkthemes &

# notify-send -h string:x-canonical-private-synchronous:hypr-cfg -u low -i ~/.config/icons/svg/free/cil-check-circle.svg 'Refreshing Environment' 'Varix has been refreshed'
