# Shell variables
# Generated by 'wal'
wallpaper='/home/aaron/Pictures/Themes/1218645.jpg'

# Special
background='#090b06'
foreground='#dcd3a6'
cursor='#dcd3a6'

# Colors
color0='#090b06'
color1='#64693A'
color2='#555D48'
color3='#6F6F4C'
color4='#877853'
color5='#7C824B'
color6='#969256'
color7='#dcd3a6'
color8='#9a9374'
color9='#64693A'
color10='#555D48'
color11='#6F6F4C'
color12='#877853'
color13='#7C824B'
color14='#969256'
color15='#dcd3a6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
