# Shell variables
# Generated by 'wal'
wallpaper='/home/aaron/Pictures/Themes/9070071.png'

# Special
background='#041516'
foreground='#c5f1db'
cursor='#c5f1db'

# Colors
color0='#041516'
color1='#179C9C'
color2='#5DA59F'
color3='#4BD9BF'
color4='#A0AB9B'
color5='#A3DA9E'
color6='#E2ECAB'
color7='#c5f1db'
color8='#89a899'
color9='#179C9C'
color10='#5DA59F'
color11='#4BD9BF'
color12='#A0AB9B'
color13='#A3DA9E'
color14='#E2ECAB'
color15='#c5f1db'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
