#!/usr/bin/env bash

bombadil link

# Find the PID of the waybar process
WAYBAR_PID=$(pgrep waybar)
SWAYNC_PID=$(pgrep swaync-client)

# If waybar is running, kill it
if [ -n "$WAYBAR_PID" ]; then
    kill "$WAYBAR_PID"
fi

# If waybar is running, kill it
if [ -n "$SWAYNC_PID" ]; then
    kill "$SWAYNC_PID"
fi

nohup ~/.config/hypr/scripts/statusbar &>/dev/null &

swaync-client --reload-config
swaync-client --reload-css

~/.config/walthings/walthings.sh --refresh

notify-send -h string:x-canonical-private-synchronous:hypr-cfg -u low -i ~/.config/icons/svg/free/cil-check-circle.svg 'Refreshing Environment' 'Dotfiles, Waybar, SwayNC and Walthings synched.'
