#!/usr/bin/env bash

# gtk-3.0 : colors
		cat > ${PATH_GTK3}/gtk.css <<- EOF
		/** ********** Colors ********** **/
		@define-color window_bg_color ${background};
		@define-color window_fg_color ${foreground};
		@define-color view_bg_color ${background};
		@define-color view_fg_color ${foreground};
		@define-color headerbar_bg_color ${modbackground[1]};
		@define-color headerbar_fg_color ${foreground};
		@define-color headerbar_border_color ${foreground};
		@define-color headerbar_backdrop_color @window_bg_color;
		@define-color headerbar_shade_color rgba(0, 0, 0, 0.36);
		@define-color headerbar_darker_shade_color rgba(0, 0, 0, 0.9);
		@define-color sidebar_bg_color ${modbackground[1]};
		@define-color sidebar_fg_color ${foreground};
		@define-color sidebar_backdrop_color ${modbackground[1]};
		@define-color sidebar_shade_color rgba(0, 0, 0, 0.25);
		@define-color sidebar_border_color rgba(0, 0, 0, 0.36);
		@define-color card_bg_color rgba(255, 255, 255, 0.08);
		@define-color card_fg_color ${foreground};
		@define-color card_shade_color rgba(0, 0, 0, 0.36);
		@define-color dialog_bg_color ${modbackground[1]};
		@define-color dialog_fg_color ${foreground};
		@define-color popover_bg_color ${modbackground[1]};
		@define-color popover_fg_color ${foreground};
		@define-color popover_shade_color rgba(0, 0, 0, 0.25);
		@define-color thumbnail_bg_color ${modbackground[1]};
		@define-color thumbnail_fg_color ${foreground};
		@define-color shade_color rgba(0, 0, 0, 0.25);
		@define-color scrollbar_outline_color rgba(0, 0, 0, 0.5);
		@define-color incognito_bg_color ${modbackground[2
		]};
		@define-color new_title_bg_color ${modbackground[1]};

		/********** Thunar * */
		.thunar .sidebar.frame { border: none; }

		.thunar .sidebar .view:selected, .thunar .sidebar iconview:selected { background-color: ${modbackground[1]}; color: ${color13}; }

		# .thunar .sidebar .view:backdrop, .thunar .sidebar iconview:backdrop { background-color: #211818; }

		.thunar .sidebar .view:backdrop:selected, .thunar .sidebar iconview:backdrop:selected { background-color:  ${modbackground[1]}; color: ${color13}; }

		.thunar .standard-view > .view, .thunar .standard-view > iconview { border-radius: 0; }

		.thunar.background, .thunar .frame {
			background-color: ${background};
		}
	EOF

	 # Copy gtk.css to gtk-dark.css
  	cp ${PATH_GTK3}/gtk.css ${PATH_GTK3}/gtk-dark.css