#!/usr/bin/env bash

# obsidian : colors
	cat > ${PATH_OBSIDIAN}/varix.css <<- _EOF_
		.theme-dark {
			--mono-rgb-0: 0, 0, 0;
			--mono-rgb-100: 255, 255, 255;
			--color-red-rgb: `pastel color $color9 | pastel format rgb`;
			--color-red: ${color9};
			--color-orange-rgb: `pastel color $color9 | pastel format rgb`;
			--color-orange: ${color9};
			--color-yellow-rgb: `pastel color $color11 | pastel format rgb`;
			--color-yellow: ${color11};
			--color-green-rgb: `pastel color $color10 | pastel format rgb`;
			--color-green: ${color10};
			--color-cyan-rgb: `pastel color $color14 | pastel format rgb`;
			--color-cyan: ${color14};
			--color-blue-rgb: `pastel color $color4 | pastel format rgb`;
			--color-blue: ${color4};
			--color-purple-rgb: `pastel color $color13 | pastel format rgb`;
			--color-purple: ${color13};
			--color-pink-rgb: `pastel color $color13 | pastel format rgb`;
			--color-pink: ${color13};
			--color-base-00: ${background};
			--color-base-05: `pastel color $background | pastel lighten 0.05 | pastel format hex`;
			--color-base-10: `pastel color $background | pastel lighten 0.10 | pastel format hex`;
			--color-base-20: `pastel color $background | pastel lighten 0.20 | pastel format hex`;
			--color-base-25: `pastel color $background | pastel lighten 0.25 | pastel format hex`;
			--color-base-30: `pastel color $background | pastel lighten 0.30 | pastel format hex`;
			--color-base-35: `pastel color $background | pastel lighten 0.35 | pastel format hex`;
			--color-base-40: `pastel color $background | pastel lighten 0.40 | pastel format hex`;
			--color-base-50: `pastel color $background | pastel lighten 0.50 | pastel format hex`;
			--color-base-60: `pastel color $background | pastel lighten 0.60 | pastel format hex`;
			--color-base-70: `pastel color $background | pastel lighten 0.70 | pastel format hex`;
			--color-base-100: `pastel color $background | pastel lighten 0.90 | pastel format hex`;
		}
	_EOF_