# Shell variables
# Generated by 'wal'
wallpaper='/home/aaron/Pictures/Themes/mr6tqwr81q8d1.png'

# Special
background='#0E082E'
foreground='#a1cae5'
cursor='#a1cae5'

# Colors
color0='#0E082E'
color1='#0912AD'
color2='#5325A6'
color3='#0E27D0'
color4='#195CEA'
color5='#4455C2'
color6='#9E48D6'
color7='#a1cae5'
color8='#708da0'
color9='#0912AD'
color10='#5325A6'
color11='#0E27D0'
color12='#195CEA'
color13='#4455C2'
color14='#9E48D6'
color15='#a1cae5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
