# Shell variables
# Generated by 'wal'
wallpaper='/home/aaron/Pictures/Themes/HEROSCREEN-BACKGROUND300724 (2).png'

# Special
background='#0A0E0E'
foreground='#a9cfcd'
cursor='#a9cfcd'

# Colors
color0='#0A0E0E'
color1='#525946'
color2='#DA5243'
color3='#E2AA26'
color4='#FDCB24'
color5='#578F89'
color6='#529490'
color7='#a9cfcd'
color8='#76908f'
color9='#525946'
color10='#DA5243'
color11='#E2AA26'
color12='#FDCB24'
color13='#578F89'
color14='#529490'
color15='#a9cfcd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
