# Shell variables
# Generated by 'wal'
wallpaper='/home/aaron/Pictures/Themes/bikers-journey-desert-wallpaper.png'

# Special
background='#10121e'
foreground='#93c7da'
cursor='#93c7da'

# Colors
color0='#10121e'
color1='#025386'
color2='#066D9D'
color3='#5B798F'
color4='#877D84'
color5='#208CB4'
color6='#5E8DA6'
color7='#93c7da'
color8='#668b98'
color9='#025386'
color10='#066D9D'
color11='#5B798F'
color12='#877D84'
color13='#208CB4'
color14='#5E8DA6'
color15='#93c7da'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
