#!/usr/bin/env bash

# TODO: Put a default wallpaper inside of Varix
WALLPAPER='/home/aaron/Pictures/Themes/SAMURAI-FIGHT-422023.png'

killall swaybg

swaybg --output '*' --mode fill --image "$WALLPAPER"
