#!/usr/bin/env bash

# TODO: Put a default wallpaper inside of Varix
WALLPAPER='/home/aaron/Pictures/Themes/aesthetic-modern-3840x2160-12476.jpg'

killall swaybg

swaybg --output '*' --mode fill --image "$WALLPAPER"
