#!/usr/bin/env bash

# TODO: Put a default wallpaper inside of Varix
WALLPAPER='/home/aaron/Pictures/Themes/heroscreen-painting-A-lone-deer-standing-in-a-serene- (1).png'

killall swaybg

swaybg --output '*' --mode fill --image "$WALLPAPER"
