#!/bin/bash

swayidle -w \
timeout 600 ' ~/.config/varix/scripts/lockscreen ' \
timeout 900 ' hyprctl dispatch dpms off' \
resume ' hyprctl dispatch dpms on' \
timeout 12000 'systemctl suspend' \
before-sleep '~/.config/varix/scripts/lockscreen '
