#!/usr/bin/env bash

# Btop Theme:
	cat > ~/.config/btop/themes/varix.theme <<- EOF
		# Main background, empty for terminal default, need to be empty if you want transparent background
		theme[main_bg]="${background}"
		
		# Main text color
		theme[main_fg]="${foreground}"
		
		# Title color for boxes
		theme[title]="${color4}"
		
		# Highlight color for keyboard shortcuts
		theme[hi_fg]="${color5}"
		
		# Background color of selected item in processes box
		theme[selected_bg]="#45475a"
		
		# Foreground color of selected item in processes box
		theme[selected_fg]="${color5}"
		
		# Color of inactive/disabled text
		theme[inactive_fg]="#7f849c"
		
		# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
		theme[graph_text]="${altforeground}"
		
		# Background color of the percentage meters
		theme[meter_bg]="${modbackground[2]}"
		
		# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
		theme[proc_misc]="${color3}"
		
		# CPU, Memory, Network, Proc box outline colors
		theme[cpu_box]="${color5}" #Mauve
		theme[mem_box]="${color2}" #Green
		theme[net_box]="${color6}" #Maroon
		theme[proc_box]="${color5}" #Blue
		
		# Box divider line and small boxes line color
		theme[div_line]="${color5}"
		
		# Temperature graph color (Green -> Yellow -> Red)
		theme[temp_start]="${color2}"
		theme[temp_mid]="${color3}"
		theme[temp_end]="${color1}"
		
		# CPU graph colors (Teal -> Lavender)
		theme[cpu_start]="${color6}"
		theme[cpu_mid]="${color5}"
		theme[cpu_end]="${color4}"
		
		# Mem/Disk free meter (Mauve -> Lavender -> Blue)
		theme[free_start]="${color5}"
		theme[free_mid]="#b4befe"
		theme[free_end]="${color5}"
		
		# Mem/Disk cached meter (Sapphire -> Lavender)
		theme[cached_start]="${color9}"
		theme[cached_mid]="${color11}"
		theme[cached_end]="${color12}"
		
		# Mem/Disk available meter (Peach -> Red)
		theme[available_start]="#fab387"
		theme[available_mid]="${color6}"
		theme[available_end]="#f38ba8"
		
		# Mem/Disk used meter (Green -> Sky)
		theme[used_start]="${color2}"
		theme[used_mid]="#94e2d5"
		theme[used_end]="#89dceb"
		
		# Download graph colors (Peach -> Red)
		theme[download_start]="#fab387"
		theme[download_mid]="${color6}"
		theme[download_end]="#f38ba8"
		
		# Upload graph colors (Green -> Sky)
		theme[upload_start]="${color2}"
		theme[upload_mid]="#94e2d5"
		theme[upload_end]="#89dceb"
		
		# Process box color gradient for threads, mem and cpu usage (Sapphire -> Mauve)
		theme[process_start]="#74c7ec"
		theme[process_mid]="#b4befe"
		theme[process_end]="${color5}"
	EOF

