#!/usr/bin/env bash

# Fish : colors
	cat > ~/dotfiles/.config/fish/colors <<- EOF
		set -U fish_color_normal ${foreground}
		set -U fish_color_command ${color4}
		set -U fish_color_quote ${color2}
		set -U fish_color_redirection ${color3}
		set -U fish_color_end ${color6}
		set -U fish_color_error ${color1}
		set -U fish_color_param ${color5}
		set -U fish_color_comment ${foreground}
		set -U fish_color_match --background=brblue
		set -U fish_color_selection white --bold --background=brblack
		set -U fish_color_search_match bryellow --background=brblack
		set -U fish_color_history_current --bold
		set -U fish_color_operator ${color}
		set -U fish_color_escape ${color2}
		set -U fish_color_cwd ${color2}
		set -U fish_color_cwd_root ${color1}
		set -U fish_color_valid_path --underline
		set -U fish_color_autosuggestion quote
		set -U fish_color_user brgreen
		set -U fish_color_host normal
		set -U fish_color_cancel --reverse
		set -U fish_pager_color_prefix normal --bold --underline
		set -U fish_pager_color_progress brwhite --background=cyan
		set -U fish_pager_color_completion normal
		set -U fish_pager_color_description ${altforeground}
		set -U fish_pager_color_selected_background --background=brblack
		set -U fish_color_keyword 
		set -U fish_pager_color_background 
		set -U fish_pager_color_secondary_completion 
		set -U fish_pager_color_secondary_prefix 
		set -U fish_pager_color_selected_completion 
		set -U fish_pager_color_selected_prefix 
		set -U fish_pager_color_selected_description 
		set -U fish_color_option 
		set -U fish_pager_color_secondary_description 
		set -U fish_color_host_remote 
		set -U fish_pager_color_secondary_background 
	EOF

