#!/usr/bin/env bash

# swaync: theme
sed -i "$HOME/dotfiles/.config/swaync/style.css" \
  -e "s/@define-color cc-bg.*/@define-color cc-bg ${background};/" \
  -e "s/@define-color noti-border-color.*/@define-color noti-border-color ${color7};/" \
  -e "s/@define-color noti-bg-opaque.*/@define-color noti-bg-opaque ${color0};/" \
  -e "s/@define-color noti-bg-darker.*/@define-color noti-bg-darker ${background};/" \
  -e "s/@define-color noti-bg-hover.*/@define-color noti-bg-hover ${modbackground[1]};/" \
  -e "s/@define-color noti-bg-hover-opaque.*/@define-color noti-bg-hover-opaque ${color0};/" \
  -e "s/@define-color noti-bg-focus.*/@define-color noti-bg-focus ${modbackground[1]};/" \
  -e "s/@define-color noti-bg .*/@define-color noti-bg ${background};/" \
  -e "s/@define-color noti-close-bg-hover.*/@define-color noti-close-bg-hover ${color6};/" \
  -e "s/@define-color noti-close-bg.*/@define-color noti-close-bg ${color0};/" \
  -e "s/@define-color text-color-disabled rgba.*/@define-color text-color-disabled ${color6};/" \
  -e "s/@define-color text-color.*/@define-color text-color ${foreground};/" \
  -e "s/@define-color bg-selected.*/@define-color bg-selected ${color6};/"

swaync-client --reload-css
