#!/usr/bin/env bash
# zed : colors
	cat > $HOME/.config/zed/themes/varix.json <<- EOF

	{
	  "$schema": "https://zed.dev/schema/themes/v0.1.0.json",
	  "name": "Varix",
	  "author": "Andrew Tec <andrewtec@enjoi.dev>, <ulinaaron@gmail.com>",
	  "themes": [
	    {
	      "name": "Varix Latte",
	      "appearance": "light",
	      "style": {
	        "border": "#ccd0da",
	        "border.variant": "#9658eb",
	        "border.focused": "#7287fd",
	        "border.selected": "#8839ef",
	        "border.transparent": "#40a02b",
	        "border.disabled": "#acb0be",
	        "elevated_surface.background": "#e6e9ef",
	        "surface.background": "#eff1f5",
	        "background": "#eff1f5",
	        "element.background": "#dce0e8",
	        "element.hover": "#9ca0b04d",
	        "element.active": "#8839ef33",
	        "element.selected": "#ccd0da99",
	        "element.disabled": "#9ca0b0",
	        "drop_target.background": "#8839ef66",
	        "ghost_element.background": null,
	        "ghost_element.hover": "#acb0be4d",
	        "ghost_element.active": "#acb0be80",
	        "ghost_element.selected": "#9ca0b059",
	        "ghost_element.disabled": "#9ca0b0",
	        "text": "#4c4f69",
	        "text.muted": "#5c5f77",
	        "text.placeholder": "#acb0be",
	        "text.disabled": "#9ca0b0",
	        "text.accent": "#8839ef",
	        "icon": "#4c4f69",
	        "icon.muted": "#8c8fa1",
	        "icon.disabled": "#9ca0b0",
	        "icon.placeholder": "#acb0be",
	        "icon.accent": "#8839ef",
	        "status_bar.background": "#dce0e8",
	        "title_bar.background": "#dce0e8",
	        "title_bar.inactive_background": "#dce0e8d9",
	        "toolbar.background": "#eff1f5",
	        "tab_bar.background": "#dce0e8",
	        "tab.inactive_background": "#e6e9ef",
	        "tab.active_background": "#eff1f5",
	        "search.match_background": "#17929933",
	        "panel.background": "#e6e9ef",
	        "panel.focused_border": "#4c4f69",
	        "pane.focused_border": "#4c4f69",
	        "scrollbar.thumb.background": "#8839ef33",
	        "scrollbar.thumb.hover_background": "#9ca0b0",
	        "scrollbar.thumb.border": "#acb0be80",
	        "scrollbar.track.background": "#eff1f5",
	        "scrollbar.track.border": "#4c4f6912",
	        "editor.foreground": "#4c4f69",
	        "editor.background": "#eff1f5",
	        "editor.gutter.background": "#eff1f5",
	        "editor.subheader.background": "#e6e9ef",
	        "editor.active_line.background": "#4c4f690d",
	        "editor.highlighted_line.background": null,
	        "editor.line_number": "#8c8fa1",
	        "editor.active_line_number": "#8839ef",
	        "editor.invisible": "#7c7f9366",
	        "editor.wrap_guide": "#acb0be",
	        "editor.active_wrap_guide": "#acb0be",
	        "editor.document_highlight.read_background": "#6c6f8529",
	        "editor.document_highlight.write_background": "#6c6f8529",
	        "terminal.background": "#eff1f5",
	        "terminal.foreground": "#4c4f69",
	        "terminal.dim_foreground": "#8c8fa1",
	        "terminal.bright_foreground": "#4c4f69",
	        "terminal.ansi.black": "#bcc0cc",
	        "terminal.ansi.red": "#d20f39",
	        "terminal.ansi.green": "#40a02b",
	        "terminal.ansi.yellow": "#df8e1d",
	        "terminal.ansi.blue": "#1e66f5",
	        "terminal.ansi.magenta": "#ea76cb",
	        "terminal.ansi.cyan": "#179299",
	        "terminal.ansi.white": "#4c4f69",
	        "terminal.ansi.bright_black": "#acb0be",
	        "terminal.ansi.bright_red": "#d20f39",
	        "terminal.ansi.bright_green": "#40a02b",
	        "terminal.ansi.bright_yellow": "#df8e1d",
	        "terminal.ansi.bright_blue": "#1e66f5",
	        "terminal.ansi.bright_magenta": "#ea76cb",
	        "terminal.ansi.bright_cyan": "#179299",
	        "terminal.ansi.bright_white": "#6c6f85",
	        "terminal.ansi.dim_black": "#bcc0cc",
	        "terminal.ansi.dim_red": "#d20f39",
	        "terminal.ansi.dim_green": "#40a02b",
	        "terminal.ansi.dim_yellow": "#df8e1d",
	        "terminal.ansi.dim_blue": "#1e66f5",
	        "terminal.ansi.dim_magenta": "#ea76cb",
	        "terminal.ansi.dim_cyan": "#179299",
	        "terminal.ansi.dim_white": "#5c5f77",
	        "link_text.hover": "#04a5e5",
	        "conflict": "#8839ef",
	        "conflict.border": "#8839ef",
	        "conflict.background": "#e6e9ef",
	        "created": "#40a02b",
	        "created.border": "#40a02b",
	        "created.background": "#e6e9ef",
	        "deleted": "#d20f39",
	        "deleted.border": "#d20f39",
	        "deleted.background": "#e6e9ef",
	        "error": "#d20f39",
	        "error.border": "#d20f39",
	        "error.background": "#e6e9ef",
	        "hidden": "#9ca0b0",
	        "hidden.border": "#9ca0b0",
	        "hidden.background": "#e6e9ef",
	        "hint": "#acb0be",
	        "hint.border": "#acb0be",
	        "hint.background": "#e6e9ef",
	        "ignored": "#9ca0b0",
	        "ignored.border": "#9ca0b0",
	        "ignored.background": "#e6e9ef",
	        "info": "#179299",
	        "info.border": "#179299",
	        "info.background": "#8839ef66",
	        "modified": "#df8e1d",
	        "modified.border": "#df8e1d",
	        "modified.background": "#e6e9ef",
	        "predictive": "#acb0be",
	        "predictive.border": "#acb0be",
	        "predictive.background": "#e6e9ef",
	        "renamed": "#209fb5",
	        "renamed.border": "#209fb5",
	        "renamed.background": "#e6e9ef",
	        "success": "#40a02b",
	        "success.border": "#40a02b",
	        "success.background": "#e6e9ef",
	        "unreachable": "#d20f39",
	        "unreachable.border": "#d20f39",
	        "unreachable.background": "#e6e9ef",
	        "warning": "#fe640b",
	        "warning.border": "#fe640b",
	        "warning.background": "#e6e9ef",
	        "players": [
	          {
	            "cursor": "#dc8a78",
	            "selection": "#acb0be80",
	            "background": "#dc8a78"
	          },
	          {
	            "cursor": "#3b6f87",
	            "selection": "#3b6f8733",
	            "background": "#3b6f87"
	          },
	          {
	            "cursor": "#823556",
	            "selection": "#82355633",
	            "background": "#823556"
	          },
	          {
	            "cursor": "#37697c",
	            "selection": "#37697c33",
	            "background": "#37697c"
	          },
	          {
	            "cursor": "#945743",
	            "selection": "#94574333",
	            "background": "#945743"
	          },
	          {
	            "cursor": "#87684b",
	            "selection": "#87684b33",
	            "background": "#87684b"
	          },
	          {
	            "cursor": "#3a58a1",
	            "selection": "#3a58a133",
	            "background": "#3a58a1"
	          },
	          {
	            "cursor": "#486f50",
	            "selection": "#486f5033",
	            "background": "#486f50"
	          }
	        ],
	        "syntax": {
	          "attribute": {
	            "color": "#df8e1d",
	            "font_style": null,
	            "font_weight": null
	          },
	          "boolean": {
	            "color": "#fe640b",
	            "font_style": null,
	            "font_weight": null
	          },
	          "comment": {
	            "color": "#8c8fa1",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "comment.doc": {
	            "color": "#8c8fa1",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "constant": {
	            "color": "#fe640b",
	            "font_style": null,
	            "font_weight": null
	          },
	          "constructor": {
	            "color": "#1e66f5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "embedded": {
	            "color": "#e64553",
	            "font_style": null,
	            "font_weight": null
	          },
	          "emphasis": {
	            "color": "#d20f39",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "emphasis.strong": {
	            "color": "#d20f39",
	            "font_style": null,
	            "font_weight": 700
	          },
	          "enum": {
	            "color": "#179299",
	            "font_style": null,
	            "font_weight": 700
	          },
	          "function": {
	            "color": "#1e66f5",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "hint": {
	            "color": "#179299",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "keyword": {
	            "color": "#8839ef",
	            "font_style": null,
	            "font_weight": null
	          },
	          "link_text": {
	            "color": "#1e66f5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "link_uri": {
	            "color": "#1e66f5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "number": {
	            "color": "#fe640b",
	            "font_style": null,
	            "font_weight": null
	          },
	          "operator": {
	            "color": "#04a5e5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "predictive": {
	            "color": "#acb0be",
	            "font_style": null,
	            "font_weight": null
	          },
	          "predoc": {
	            "color": "#d20f39",
	            "font_style": null,
	            "font_weight": null
	          },
	          "primary": {
	            "color": "#e64553",
	            "font_style": null,
	            "font_weight": null
	          },
	          "property": {
	            "color": "#1e66f5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation": {
	            "color": "#179299",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.bracket": {
	            "color": "#179299",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.delimiter": {
	            "color": "#7c7f93",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.list_marker": {
	            "color": "#179299",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.special": {
	            "color": "#179299",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.special.symbol": {
	            "color": "#d20f39",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string": {
	            "color": "#40a02b",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.escape": {
	            "color": "#ea76cb",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.regex": {
	            "color": "#ea76cb",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.special": {
	            "color": "#ea76cb",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.special.symbol": {
	            "color": "#dd7878",
	            "font_style": null,
	            "font_weight": null
	          },
	          "tag": {
	            "color": "#1e66f5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "text.literal": {
	            "color": "#40a02b",
	            "font_style": null,
	            "font_weight": null
	          },
	          "title": {
	            "color": "#4c4f69",
	            "font_style": null,
	            "font_weight": 800
	          },
	          "type": {
	            "color": "#df8e1d",
	            "font_style": null,
	            "font_weight": null
	          },
	          "type.interface": {
	            "color": "#df8e1d",
	            "font_style": null,
	            "font_weight": null
	          },
	          "type.super": {
	            "color": "#df8e1d",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable": {
	            "color": "#4c4f69",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable.member": {
	            "color": "#4c4f69",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable.parameter": {
	            "color": "#fe640b",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "variable.special": {
	            "color": "#823556",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "variant": {
	            "color": "#d20f39",
	            "font_style": null,
	            "font_weight": null
	          }
	        }
	      }
	    },
	    {
	      "name": "Varix Frappé",
	      "appearance": "dark",
	      "style": {
	        "border": "#414559",
	        "border.variant": "#af8cca",
	        "border.focused": "#babbf1",
	        "border.selected": "#ca9ee6",
	        "border.transparent": "#a6d189",
	        "border.disabled": "#626880",
	        "elevated_surface.background": "#292c3c",
	        "surface.background": "#303446",
	        "background": "#303446",
	        "element.background": "#232634",
	        "element.hover": "#7379944d",
	        "element.active": "#ca9ee633",
	        "element.selected": "#41455999",
	        "element.disabled": "#737994",
	        "drop_target.background": "#ca9ee666",
	        "ghost_element.background": null,
	        "ghost_element.hover": "#6268804d",
	        "ghost_element.active": "#62688080",
	        "ghost_element.selected": "#73799459",
	        "ghost_element.disabled": "#737994",
	        "text": "#c6d0f5",
	        "text.muted": "#b5bfe2",
	        "text.placeholder": "#626880",
	        "text.disabled": "#737994",
	        "text.accent": "#ca9ee6",
	        "icon": "#c6d0f5",
	        "icon.muted": "#838ba7",
	        "icon.disabled": "#737994",
	        "icon.placeholder": "#626880",
	        "icon.accent": "#ca9ee6",
	        "status_bar.background": "#232634",
	        "title_bar.background": "#232634",
	        "title_bar.inactive_background": "#232634d9",
	        "toolbar.background": "#303446",
	        "tab_bar.background": "#232634",
	        "tab.inactive_background": "#292c3c",
	        "tab.active_background": "#303446",
	        "search.match_background": "#81c8be33",
	        "panel.background": "#292c3c",
	        "panel.focused_border": "#c6d0f5",
	        "pane.focused_border": "#c6d0f5",
	        "scrollbar.thumb.background": "#ca9ee633",
	        "scrollbar.thumb.hover_background": "#737994",
	        "scrollbar.thumb.border": "#62688080",
	        "scrollbar.track.background": "#303446",
	        "scrollbar.track.border": "#c6d0f512",
	        "editor.foreground": "#c6d0f5",
	        "editor.background": "#303446",
	        "editor.gutter.background": "#303446",
	        "editor.subheader.background": "#292c3c",
	        "editor.active_line.background": "#c6d0f50d",
	        "editor.highlighted_line.background": null,
	        "editor.line_number": "#838ba7",
	        "editor.active_line_number": "#ca9ee6",
	        "editor.invisible": "#949cbb66",
	        "editor.wrap_guide": "#626880",
	        "editor.active_wrap_guide": "#626880",
	        "editor.document_highlight.read_background": "#a5adce29",
	        "editor.document_highlight.write_background": "#a5adce29",
	        "terminal.background": "#303446",
	        "terminal.foreground": "#c6d0f5",
	        "terminal.dim_foreground": "#838ba7",
	        "terminal.bright_foreground": "#c6d0f5",
	        "terminal.ansi.black": "#51576d",
	        "terminal.ansi.red": "#e78284",
	        "terminal.ansi.green": "#a6d189",
	        "terminal.ansi.yellow": "#e5c890",
	        "terminal.ansi.blue": "#8caaee",
	        "terminal.ansi.magenta": "#f4b8e4",
	        "terminal.ansi.cyan": "#81c8be",
	        "terminal.ansi.white": "#c6d0f5",
	        "terminal.ansi.bright_black": "#626880",
	        "terminal.ansi.bright_red": "#e78284",
	        "terminal.ansi.bright_green": "#a6d189",
	        "terminal.ansi.bright_yellow": "#e5c890",
	        "terminal.ansi.bright_blue": "#8caaee",
	        "terminal.ansi.bright_magenta": "#f4b8e4",
	        "terminal.ansi.bright_cyan": "#81c8be",
	        "terminal.ansi.bright_white": "#a5adce",
	        "terminal.ansi.dim_black": "#51576d",
	        "terminal.ansi.dim_red": "#e78284",
	        "terminal.ansi.dim_green": "#a6d189",
	        "terminal.ansi.dim_yellow": "#e5c890",
	        "terminal.ansi.dim_blue": "#8caaee",
	        "terminal.ansi.dim_magenta": "#f4b8e4",
	        "terminal.ansi.dim_cyan": "#81c8be",
	        "terminal.ansi.dim_white": "#b5bfe2",
	        "link_text.hover": "#99d1db",
	        "conflict": "#ca9ee6",
	        "conflict.border": "#ca9ee6",
	        "conflict.background": "#292c3c",
	        "created": "#a6d189",
	        "created.border": "#a6d189",
	        "created.background": "#292c3c",
	        "deleted": "#e78284",
	        "deleted.border": "#e78284",
	        "deleted.background": "#292c3c",
	        "error": "#e78284",
	        "error.border": "#e78284",
	        "error.background": "#292c3c",
	        "hidden": "#737994",
	        "hidden.border": "#737994",
	        "hidden.background": "#292c3c",
	        "hint": "#626880",
	        "hint.border": "#626880",
	        "hint.background": "#292c3c",
	        "ignored": "#737994",
	        "ignored.border": "#737994",
	        "ignored.background": "#292c3c",
	        "info": "#81c8be",
	        "info.border": "#81c8be",
	        "info.background": "#ca9ee666",
	        "modified": "#e5c890",
	        "modified.border": "#e5c890",
	        "modified.background": "#292c3c",
	        "predictive": "#626880",
	        "predictive.border": "#626880",
	        "predictive.background": "#292c3c",
	        "renamed": "#85c1dc",
	        "renamed.border": "#85c1dc",
	        "renamed.background": "#292c3c",
	        "success": "#a6d189",
	        "success.border": "#a6d189",
	        "success.background": "#292c3c",
	        "unreachable": "#e78284",
	        "unreachable.border": "#e78284",
	        "unreachable.background": "#292c3c",
	        "warning": "#ef9f76",
	        "warning.border": "#ef9f76",
	        "warning.background": "#292c3c",
	        "players": [
	          {
	            "cursor": "#f2d5cf",
	            "selection": "#62688080",
	            "background": "#f2d5cf"
	          },
	          {
	            "cursor": "#accaeb",
	            "selection": "#accaeb33",
	            "background": "#accaeb"
	          },
	          {
	            "cursor": "#d3b1c8",
	            "selection": "#d3b1c833",
	            "background": "#d3b1c8"
	          },
	          {
	            "cursor": "#abcddf",
	            "selection": "#abcddf33",
	            "background": "#abcddf"
	          },
	          {
	            "cursor": "#d7bdc2",
	            "selection": "#d7bdc233",
	            "background": "#d7bdc2"
	          },
	          {
	            "cursor": "#d3cdcd",
	            "selection": "#d3cdcd33",
	            "background": "#d3cdcd"
	          },
	          {
	            "cursor": "#afc1f2",
	            "selection": "#afc1f233",
	            "background": "#afc1f2"
	          },
	          {
	            "cursor": "#b9d1ca",
	            "selection": "#b9d1ca33",
	            "background": "#b9d1ca"
	          }
	        ],
	        "syntax": {
	          "attribute": {
	            "color": "#e5c890",
	            "font_style": null,
	            "font_weight": null
	          },
	          "boolean": {
	            "color": "#ef9f76",
	            "font_style": null,
	            "font_weight": null
	          },
	          "comment": {
	            "color": "#838ba7",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "comment.doc": {
	            "color": "#838ba7",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "constant": {
	            "color": "#ef9f76",
	            "font_style": null,
	            "font_weight": null
	          },
	          "constructor": {
	            "color": "#8caaee",
	            "font_style": null,
	            "font_weight": null
	          },
	          "embedded": {
	            "color": "#ea999c",
	            "font_style": null,
	            "font_weight": null
	          },
	          "emphasis": {
	            "color": "#e78284",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "emphasis.strong": {
	            "color": "#e78284",
	            "font_style": null,
	            "font_weight": 700
	          },
	          "enum": {
	            "color": "#81c8be",
	            "font_style": null,
	            "font_weight": 700
	          },
	          "function": {
	            "color": "#8caaee",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "hint": {
	            "color": "#81c8be",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "keyword": {
	            "color": "#ca9ee6",
	            "font_style": null,
	            "font_weight": null
	          },
	          "link_text": {
	            "color": "#8caaee",
	            "font_style": null,
	            "font_weight": null
	          },
	          "link_uri": {
	            "color": "#8caaee",
	            "font_style": null,
	            "font_weight": null
	          },
	          "number": {
	            "color": "#ef9f76",
	            "font_style": null,
	            "font_weight": null
	          },
	          "operator": {
	            "color": "#99d1db",
	            "font_style": null,
	            "font_weight": null
	          },
	          "predictive": {
	            "color": "#626880",
	            "font_style": null,
	            "font_weight": null
	          },
	          "predoc": {
	            "color": "#e78284",
	            "font_style": null,
	            "font_weight": null
	          },
	          "primary": {
	            "color": "#ea999c",
	            "font_style": null,
	            "font_weight": null
	          },
	          "property": {
	            "color": "#8caaee",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation": {
	            "color": "#81c8be",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.bracket": {
	            "color": "#81c8be",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.delimiter": {
	            "color": "#949cbb",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.list_marker": {
	            "color": "#81c8be",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.special": {
	            "color": "#81c8be",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.special.symbol": {
	            "color": "#e78284",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string": {
	            "color": "#a6d189",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.escape": {
	            "color": "#f4b8e4",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.regex": {
	            "color": "#f4b8e4",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.special": {
	            "color": "#f4b8e4",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.special.symbol": {
	            "color": "#eebebe",
	            "font_style": null,
	            "font_weight": null
	          },
	          "tag": {
	            "color": "#8caaee",
	            "font_style": null,
	            "font_weight": null
	          },
	          "text.literal": {
	            "color": "#a6d189",
	            "font_style": null,
	            "font_weight": null
	          },
	          "title": {
	            "color": "#c6d0f5",
	            "font_style": null,
	            "font_weight": 800
	          },
	          "type": {
	            "color": "#e5c890",
	            "font_style": null,
	            "font_weight": null
	          },
	          "type.interface": {
	            "color": "#e5c890",
	            "font_style": null,
	            "font_weight": null
	          },
	          "type.super": {
	            "color": "#e5c890",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable": {
	            "color": "#c6d0f5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable.member": {
	            "color": "#c6d0f5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable.parameter": {
	            "color": "#ef9f76",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "variable.special": {
	            "color": "#d3b1c8",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "variant": {
	            "color": "#e78284",
	            "font_style": null,
	            "font_weight": null
	          }
	        }
	      }
	    },
	    {
	      "name": "Varix Macchiato",
	      "appearance": "dark",
	      "style": {
	        "border": "#363a4f",
	        "border.variant": "#a98cd5",
	        "border.focused": "#b7bdf8",
	        "border.selected": "#c6a0f6",
	        "border.transparent": "#a6da95",
	        "border.disabled": "#5b6078",
	        "elevated_surface.background": "#1e2030",
	        "surface.background": "#24273a",
	        "background": "#24273a",
	        "element.background": "#181926",
	        "element.hover": "#6e738d4d",
	        "element.active": "#c6a0f633",
	        "element.selected": "#363a4f99",
	        "element.disabled": "#6e738d",
	        "drop_target.background": "#c6a0f666",
	        "ghost_element.background": null,
	        "ghost_element.hover": "#5b60784d",
	        "ghost_element.active": "#5b607880",
	        "ghost_element.selected": "#6e738d59",
	        "ghost_element.disabled": "#6e738d",
	        "text": "#cad3f5",
	        "text.muted": "#b8c0e0",
	        "text.placeholder": "#5b6078",
	        "text.disabled": "#6e738d",
	        "text.accent": "#c6a0f6",
	        "icon": "#cad3f5",
	        "icon.muted": "#8087a2",
	        "icon.disabled": "#6e738d",
	        "icon.placeholder": "#5b6078",
	        "icon.accent": "#c6a0f6",
	        "status_bar.background": "#181926",
	        "title_bar.background": "#181926",
	        "title_bar.inactive_background": "#181926d9",
	        "toolbar.background": "#24273a",
	        "tab_bar.background": "#181926",
	        "tab.inactive_background": "#1e2030",
	        "tab.active_background": "#24273a",
	        "search.match_background": "#8bd5ca33",
	        "panel.background": "#1e2030",
	        "panel.focused_border": "#cad3f5",
	        "pane.focused_border": "#cad3f5",
	        "scrollbar.thumb.background": "#c6a0f633",
	        "scrollbar.thumb.hover_background": "#6e738d",
	        "scrollbar.thumb.border": "#5b607880",
	        "scrollbar.track.background": "#24273a",
	        "scrollbar.track.border": "#cad3f512",
	        "editor.foreground": "#cad3f5",
	        "editor.background": "#24273a",
	        "editor.gutter.background": "#24273a",
	        "editor.subheader.background": "#1e2030",
	        "editor.active_line.background": "#cad3f50d",
	        "editor.highlighted_line.background": null,
	        "editor.line_number": "#8087a2",
	        "editor.active_line_number": "#c6a0f6",
	        "editor.invisible": "#939ab766",
	        "editor.wrap_guide": "#5b6078",
	        "editor.active_wrap_guide": "#5b6078",
	        "editor.document_highlight.read_background": "#a5adcb29",
	        "editor.document_highlight.write_background": "#a5adcb29",
	        "terminal.background": "#24273a",
	        "terminal.foreground": "#cad3f5",
	        "terminal.dim_foreground": "#8087a2",
	        "terminal.bright_foreground": "#cad3f5",
	        "terminal.ansi.black": "#494d64",
	        "terminal.ansi.red": "#ed8796",
	        "terminal.ansi.green": "#a6da95",
	        "terminal.ansi.yellow": "#eed49f",
	        "terminal.ansi.blue": "#8aadf4",
	        "terminal.ansi.magenta": "#f5bde6",
	        "terminal.ansi.cyan": "#8bd5ca",
	        "terminal.ansi.white": "#cad3f5",
	        "terminal.ansi.bright_black": "#5b6078",
	        "terminal.ansi.bright_red": "#ed8796",
	        "terminal.ansi.bright_green": "#a6da95",
	        "terminal.ansi.bright_yellow": "#eed49f",
	        "terminal.ansi.bright_blue": "#8aadf4",
	        "terminal.ansi.bright_magenta": "#f5bde6",
	        "terminal.ansi.bright_cyan": "#8bd5ca",
	        "terminal.ansi.bright_white": "#a5adcb",
	        "terminal.ansi.dim_black": "#494d64",
	        "terminal.ansi.dim_red": "#ed8796",
	        "terminal.ansi.dim_green": "#a6da95",
	        "terminal.ansi.dim_yellow": "#eed49f",
	        "terminal.ansi.dim_blue": "#8aadf4",
	        "terminal.ansi.dim_magenta": "#f5bde6",
	        "terminal.ansi.dim_cyan": "#8bd5ca",
	        "terminal.ansi.dim_white": "#b8c0e0",
	        "link_text.hover": "#91d7e3",
	        "conflict": "#c6a0f6",
	        "conflict.border": "#c6a0f6",
	        "conflict.background": "#1e2030",
	        "created": "#a6da95",
	        "created.border": "#a6da95",
	        "created.background": "#1e2030",
	        "deleted": "#ed8796",
	        "deleted.border": "#ed8796",
	        "deleted.background": "#1e2030",
	        "error": "#ed8796",
	        "error.border": "#ed8796",
	        "error.background": "#1e2030",
	        "hidden": "#6e738d",
	        "hidden.border": "#6e738d",
	        "hidden.background": "#1e2030",
	        "hint": "#5b6078",
	        "hint.border": "#5b6078",
	        "hint.background": "#1e2030",
	        "ignored": "#6e738d",
	        "ignored.border": "#6e738d",
	        "ignored.background": "#1e2030",
	        "info": "#8bd5ca",
	        "info.border": "#8bd5ca",
	        "info.background": "#c6a0f666",
	        "modified": "#eed49f",
	        "modified.border": "#eed49f",
	        "modified.background": "#1e2030",
	        "predictive": "#5b6078",
	        "predictive.border": "#5b6078",
	        "predictive.background": "#1e2030",
	        "renamed": "#7dc4e4",
	        "renamed.border": "#7dc4e4",
	        "renamed.background": "#1e2030",
	        "success": "#a6da95",
	        "success.border": "#a6da95",
	        "success.background": "#1e2030",
	        "unreachable": "#ed8796",
	        "unreachable.border": "#ed8796",
	        "unreachable.background": "#1e2030",
	        "warning": "#f5a97f",
	        "warning.border": "#f5a97f",
	        "warning.background": "#1e2030",
	        "players": [
	          {
	            "cursor": "#f4dbd6",
	            "selection": "#5b607880",
	            "background": "#f4dbd6"
	          },
	          {
	            "cursor": "#abcdee",
	            "selection": "#abcdee33",
	            "background": "#abcdee"
	          },
	          {
	            "cursor": "#d8b5cf",
	            "selection": "#d8b5cf33",
	            "background": "#d8b5cf"
	          },
	          {
	            "cursor": "#b1d4e4",
	            "selection": "#b1d4e433",
	            "background": "#b1d4e4"
	          },
	          {
	            "cursor": "#dbc3c6",
	            "selection": "#dbc3c633",
	            "background": "#dbc3c6"
	          },
	          {
	            "cursor": "#d8d4d3",
	            "selection": "#d8d4d333",
	            "background": "#d8d4d3"
	          },
	          {
	            "cursor": "#b0c4f5",
	            "selection": "#b0c4f533",
	            "background": "#b0c4f5"
	          },
	          {
	            "cursor": "#bbd6cf",
	            "selection": "#bbd6cf33",
	            "background": "#bbd6cf"
	          }
	        ],
	        "syntax": {
	          "attribute": {
	            "color": "#eed49f",
	            "font_style": null,
	            "font_weight": null
	          },
	          "boolean": {
	            "color": "#f5a97f",
	            "font_style": null,
	            "font_weight": null
	          },
	          "comment": {
	            "color": "#8087a2",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "comment.doc": {
	            "color": "#8087a2",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "constant": {
	            "color": "#f5a97f",
	            "font_style": null,
	            "font_weight": null
	          },
	          "constructor": {
	            "color": "#8aadf4",
	            "font_style": null,
	            "font_weight": null
	          },
	          "embedded": {
	            "color": "#ee99a0",
	            "font_style": null,
	            "font_weight": null
	          },
	          "emphasis": {
	            "color": "#ed8796",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "emphasis.strong": {
	            "color": "#ed8796",
	            "font_style": null,
	            "font_weight": 700
	          },
	          "enum": {
	            "color": "#8bd5ca",
	            "font_style": null,
	            "font_weight": 700
	          },
	          "function": {
	            "color": "#8aadf4",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "hint": {
	            "color": "#8bd5ca",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "keyword": {
	            "color": "#c6a0f6",
	            "font_style": null,
	            "font_weight": null
	          },
	          "link_text": {
	            "color": "#8aadf4",
	            "font_style": null,
	            "font_weight": null
	          },
	          "link_uri": {
	            "color": "#8aadf4",
	            "font_style": null,
	            "font_weight": null
	          },
	          "number": {
	            "color": "#f5a97f",
	            "font_style": null,
	            "font_weight": null
	          },
	          "operator": {
	            "color": "#91d7e3",
	            "font_style": null,
	            "font_weight": null
	          },
	          "predictive": {
	            "color": "#5b6078",
	            "font_style": null,
	            "font_weight": null
	          },
	          "predoc": {
	            "color": "#ed8796",
	            "font_style": null,
	            "font_weight": null
	          },
	          "primary": {
	            "color": "#ee99a0",
	            "font_style": null,
	            "font_weight": null
	          },
	          "property": {
	            "color": "#8aadf4",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation": {
	            "color": "#8bd5ca",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.bracket": {
	            "color": "#8bd5ca",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.delimiter": {
	            "color": "#939ab7",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.list_marker": {
	            "color": "#8bd5ca",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.special": {
	            "color": "#8bd5ca",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.special.symbol": {
	            "color": "#ed8796",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string": {
	            "color": "#a6da95",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.escape": {
	            "color": "#f5bde6",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.regex": {
	            "color": "#f5bde6",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.special": {
	            "color": "#f5bde6",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.special.symbol": {
	            "color": "#f0c6c6",
	            "font_style": null,
	            "font_weight": null
	          },
	          "tag": {
	            "color": "#8aadf4",
	            "font_style": null,
	            "font_weight": null
	          },
	          "text.literal": {
	            "color": "#a6da95",
	            "font_style": null,
	            "font_weight": null
	          },
	          "title": {
	            "color": "#cad3f5",
	            "font_style": null,
	            "font_weight": 800
	          },
	          "type": {
	            "color": "#eed49f",
	            "font_style": null,
	            "font_weight": null
	          },
	          "type.interface": {
	            "color": "#eed49f",
	            "font_style": null,
	            "font_weight": null
	          },
	          "type.super": {
	            "color": "#eed49f",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable": {
	            "color": "#cad3f5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable.member": {
	            "color": "#cad3f5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable.parameter": {
	            "color": "#f5a97f",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "variable.special": {
	            "color": "#d8b5cf",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "variant": {
	            "color": "#ed8796",
	            "font_style": null,
	            "font_weight": null
	          }
	        }
	      }
	    },
	    {
	      "name": "Varix Mocha",
	      "appearance": "dark",
	      "style": {
	        "border": "${background}",
	        "border.variant": "${color0}",
	        "border.focused": "${modbackground[2]}",
	        "border.selected": "${altforeground}",
	        "border.transparent": "${modbackground[2]}",
	        "border.disabled": "${background}e6",
	        "elevated_surface.background": "${modbackground[1]}",
	        "surface.background": "${backgroundE6}",
	        "background": "${background}D9",
	        "element.background": "${modbackground[2]}E6",
	        "element.hover": "${color1}4d",
	        "element.active": "${color1}33",
	        "element.selected": "#FFFFFF99",
	        "element.disabled": "#FFFFFF",
	        "drop_target.background": "#FFFFFF66",
	        "ghost_element.background": null,
	        "ghost_element.hover": "${background}4d",
	        "ghost_element.active": "${color3}80",
	        "ghost_element.selected": "${modbackground[2]}59",
	        "ghost_element.disabled": "#6c7086",
	        "text": "${foreground}",
	        "text.muted": "${foreground}99",
	        "text.placeholder": "${altforeground}",
	        "text.disabled": "${foreground}4D",
	        "text.accent": "${altforeground}",
	        "icon": "${foreground}",
	        "icon.muted": "${foreground}E6",
	        "icon.disabled": "${color0}",
	        "icon.placeholder": "${color3}",
	        "icon.accent": "${color4}",
	        "status_bar.background": "${modbackground[1]}",
	        "title_bar.background": "${background}",
	        "title_bar.inactive_background": "${background}d9",
	        "toolbar.background": "${modbackground[1]}",
	        "tab_bar.background": "${modbackground[1]}99",
	        "tab.inactive_background": "${modbackground[1]}",
	        "tab.active_background": "${modbackground[2]}",
	        "search.match_background": "${modbackground[1]}33",
	        "panel.background": "${modbackground[1]}80",
	        "panel.focused_border": "${color1}",
	        "pane.focused_border": "${color1}",
	        "scrollbar.thumb.background": "${modbackground[2]}80",
	        "scrollbar.thumb.hover_background": "#6c7086",
	        "scrollbar.thumb.border": "${color5}80",
	        "scrollbar.track.background": "${background[2]}",
	        "scrollbar.track.border": "${background}80",
	        "editor.foreground": "${foreground}",
	        "editor.background": "${background}4D",
	        "editor.gutter.background": "${background}E6",
	        "editor.subheader.background": "${modbackground[1]}",
	        "editor.active_line.background": "${modbackground[2]}4D",
	        "editor.highlighted_line.background": null,
	        "editor.line_number": "${foreground}4D",
	        "editor.active_line_number": "${color4}",
	        "editor.invisible": "${foreground}66",
	        "editor.wrap_guide": "${foreground}80",
	        "editor.active_wrap_guide": "${foreground}",
	        "editor.document_highlight.read_background": "${color2}29",
	        "editor.document_highlight.write_background": "${color2}29",
			"editor.indent_guide_active": "${foreground}26",
			"editor.indent_guide": "${foreground}08",
	        "terminal.background": "${background}",
	        "terminal.foreground": "${foreground}",
	        "terminal.dim_foreground": "${foreground}B3",
	        "terminal.bright_foreground": "${color7}",
	        "terminal.ansi.black": "${eblack}",
	        "terminal.ansi.red": "${ered}",
	        "terminal.ansi.green": "${egreen}",
	        "terminal.ansi.yellow": "${elyellow}",
	        "terminal.ansi.blue": "${eblue}",
	        "terminal.ansi.magenta": "${emagenta}",
	        "terminal.ansi.cyan": "${ecyan}",
	        "terminal.ansi.white": "${ewhite}",
	        "terminal.ansi.bright_black": "${elblack}",
	        "terminal.ansi.bright_red": "${elred}",
	        "terminal.ansi.bright_green": "${elgreen}",
	        "terminal.ansi.bright_yellow": "${elyellow}",
	        "terminal.ansi.bright_blue": "${elblue}",
	        "terminal.ansi.bright_magenta": "${elmagenta}",
	        "terminal.ansi.bright_cyan": "${elcyan}",
	        "terminal.ansi.bright_white": "${elwhite}",
	        "terminal.ansi.dim_black": "#45475a",
	        "terminal.ansi.dim_red": "#f38ba8",
	        "terminal.ansi.dim_green": "#a6e3a1",
	        "terminal.ansi.dim_yellow": "#f9e2af",
	        "terminal.ansi.dim_blue": "#89b4fa",
	        "terminal.ansi.dim_magenta": "#f5c2e7",
	        "terminal.ansi.dim_cyan": "#94e2d5",
	        "terminal.ansi.dim_white": "#bac2de",
	        "link_text.hover": "#89dceb",
	        "conflict": "#cba6f7",
	        "conflict.border": "#cba6f7",
	        "conflict.background": "#181825",
	        "created": "${color10}",
	        "created.border": "${color10}",
	        "created.background": "${background}",
	        "deleted": "${altforeground}",
	        "deleted.border": "${altforeground}",
	        "deleted.background": "${background}",
	        "error": "${color1}",
	        "error.border": "${color1}",
	        "error.background": "${background}",
	        "hidden": "${altforeground}",
	        "hidden.border": "${altforeground}",
	        "hidden.background": "#181825",
	        "hint": "#FFFFFF",
	        "hint.border": "#585b70",
	        "hint.background": "#181825",
	        "ignored": "${altforeground}",
	        "ignored.border": "${altforeground}",
	        "ignored.background": "#181825",
	        "info": "${color4}",
	        "info.border": "${color4}",
	        "info.background": "${modbackground[1]}66",
	        "modified": "#f9e2af",
	        "modified.border": "#f9e2af",
	        "modified.background": "#181825",
	        "predictive": "${color4}",
	        "predictive.border": "${color4}",
	        "predictive.background": "#181825",
	        "renamed": "#74c7ec",
	        "renamed.border": "#74c7ec",
	        "renamed.background": "#181825",
	        "success": "${color9}",
	        "success.border": "${color9}",
	        "success.background": "#181825",
	        "unreachable": "#f38ba8",
	        "unreachable.border": "#f38ba8",
	        "unreachable.background": "#181825",
	        "warning": "#fab387",
	        "warning.border": "#fab387",
	        "warning.background": "#181825",
	        "players": [
	          {
	            "cursor": "#f5e0dc",
	            "selection": "#FFFFFF80",
	            "background": "#f5e0dc"
	          },
	          {
	            "cursor": "#a9d0f0",
	            "selection": "#a9d0f033",
	            "background": "#a9d0f0"
	          },
	          {
	            "cursor": "${foreground}",
	            "selection": "${foreground}33",
	            "background": "${foreground}"
	          },
	          {
	            "cursor": "#b6dae7",
	            "selection": "#b6dae733",
	            "background": "#b6dae7"
	          },
	          {
	            "cursor": "#dfc8c8",
	            "selection": "#dfc8c833",
	            "background": "#dfc8c8"
	          },
	          {
	            "cursor": "#dfdad8",
	            "selection": "#dfdad833",
	            "background": "#dfdad8"
	          },
	          {
	            "cursor": "#b2c8f6",
	            "selection": "#b2c8f633",
	            "background": "#b2c8f6"
	          },
	          {
	            "cursor": "#bddbd2",
	            "selection": "#bddbd233",
	            "background": "#bddbd2"
	          }
	        ],
	        "syntax": {
	          "attribute": {
	            "color": "#f9e2af",
	            "font_style": null,
	            "font_weight": null
	          },
	          "boolean": {
	            "color": "${ecyan}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "comment": {
	            "color": "${ecomment}",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "comment.doc": {
	            "color": "#7f849c",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "constant": {
	            "color": "#fab387",
	            "font_style": null,
	            "font_weight": null
	          },
	          "constructor": {
	            "color": "#89b4fa",
	            "font_style": null,
	            "font_weight": null
	          },
	          "embedded": {
	            "color": "#eba0ac",
	            "font_style": null,
	            "font_weight": null
	          },
	          "emphasis": {
	            "color": "#f38ba8",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "emphasis.strong": {
	            "color": "#f38ba8",
	            "font_style": null,
	            "font_weight": 700
	          },
	          "enum": {
	            "color": "#94e2d5",
	            "font_style": null,
	            "font_weight": 700
	          },
	          "function": {
	            "colorp": "#89b4fa",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "hint": {
	            "color": "#94e2d5",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "keyword": {
	            "color": "${emagenta}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "link_text": {
	            "color": "#89b4fa",
	            "font_style": null,
	            "font_weight": null
	          },
	          "link_uri": {
	            "color": "#89b4fa",
	            "font_style": null,
	            "font_weight": null
	          },
	          "number": {
	            "color": "${elblue}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "operator": {
	            "color": "${eyellow}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "predictive": {
	            "color": "#585b70",
	            "font_style": null,
	            "font_weight": null
	          },
	          "predoc": {
	            "color": "#f38ba8",
	            "font_style": null,
	            "font_weight": null
	          },
	          "primary": {
	            "color": "#eba0ac",
	            "font_style": null,
	            "font_weight": null
	          },
	          "property": {
	            "color": "${eblue}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation": {
	            "color": "#94e2d5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.bracket": {
	            "color": "#94e2d5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.delimiter": {
	            "color": "#9399b2",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.list_marker": {
	            "color": "#94e2d5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.special": {
	            "color": "#94e2d5",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.special.symbol": {
	            "color": "#f38ba8",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string": {
	            "color": "${egreen}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.escape": {
	            "color": "${egreen}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.regex": {
	            "color": "${egreen}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.special": {
	            "color": "${elgreen}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.special.symbol": {
	            "color": "${egreen}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "tag": {
	            "color": "#89b4fa",
	            "font_style": null,
	            "font_weight": null
	          },
	          "text.literal": {
	            "color": "#a6e3a1",
	            "font_style": null,
	            "font_weight": null
	          },
	          "title": {
	            "color": "#cdd6f4",
	            "font_style": null,
	            "font_weight": 800
	          },
	          "type": {
	            "color": "#f9e2af",
	            "font_style": null,
	            "font_weight": null
	          },
	          "type.interface": {
	            "color": "#f9e2af",
	            "font_style": null,
	            "font_weight": null
	          },
	          "type.super": {
	            "color": "#f9e2af",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable": {
	            "color": "#cdd6f4",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable.member": {
	            "color": "#cdd6f4",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable.parameter": {
	            "color": "#fab387",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "variable.special": {
	            "color": "#dcb8d5",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "variant": {
	            "color": "#f38ba8",
	            "font_style": null,
	            "font_weight": null
	          }
	        }
	      }
	    }
	  ]
	}

	EOF
