#!/usr/bin/env bash
# zed : colors
	cat > $HOME/.config/zed/themes/varix.json <<- EOF

	{
	  "$schema": "https://zed.dev/schema/themes/v0.1.0.json",
	  "name": "Varix",
	  "author": "Andrew Tec <andrewtec@enjoi.dev>, <ulinaaron@gmail.com>",
	  "themes": [
	    {
	      "name": "Varix",
	      "appearance": "dark",
	      "style": {
	        "border": "${background}",
	        "border.variant": "${color0}",
	        "border.focused": "${modbackground[2]}",
	        "border.selected": "${altforeground}",
	        "border.transparent": "${modbackground[2]}",
	        "border.disabled": "${background}e6",
	        "elevated_surface.background": "${modbackground[1]}",
	        "surface.background": "${backgroundE6}",
	        "background": "${background}D9",
	        "element.background": "${modbackground[2]}E6",
	        "element.hover": "${color1}4d",
	        "element.active": "${color1}33",
	        "element.selected": "#FFFFFF99",
	        "element.disabled": "#FFFFFF",
	        "drop_target.background": "#FFFFFF66",
	        "ghost_element.background": null,
	        "ghost_element.hover": "${background}4d",
	        "ghost_element.active": "${color3}80",
	        "ghost_element.selected": "${modbackground[2]}59",
	        "ghost_element.disabled": "#6c7086",
	        "text": "${foreground}",
	        "text.muted": "${foreground}99",
	        "text.placeholder": "${altforeground}",
	        "text.disabled": "${foreground}4D",
	        "text.accent": "${altforeground}",
	        "icon": "${foreground}",
	        "icon.muted": "${foreground}E6",
	        "icon.disabled": "${color0}",
	        "icon.placeholder": "${color3}",
	        "icon.accent": "${color4}",
	        "status_bar.background": "${modbackground[1]}",
	        "title_bar.background": "${background}",
	        "title_bar.inactive_background": "${background}d9",
	        "toolbar.background": "${modbackground[1]}",
	        "tab_bar.background": "${modbackground[1]}99",
	        "tab.inactive_background": "${modbackground[1]}",
	        "tab.active_background": "${modbackground[2]}",
	        "search.match_background": "${modbackground[1]}33",
	        "panel.background": "${modbackground[1]}80",
	        "panel.focused_border": "${color1}",
	        "pane.focused_border": "${color1}",
	        "scrollbar.thumb.background": "${modbackground[2]}80",
	        "scrollbar.thumb.hover_background": "#6c7086",
	        "scrollbar.thumb.border": "${color5}80",
	        "scrollbar.track.background": "${background[2]}",
	        "scrollbar.track.border": "${background}80",
	        "editor.foreground": "${foreground}",
	        "editor.background": "${background}4D",
	        "editor.gutter.background": "${background}E6",
	        "editor.subheader.background": "${modbackground[1]}",
	        "editor.active_line.background": "${modbackground[2]}4D",
	        "editor.highlighted_line.background": null,
	        "editor.line_number": "${foreground}4D",
	        "editor.active_line_number": "${color4}",
	        "editor.invisible": "${foreground}66",
	        "editor.wrap_guide": "${foreground}80",
	        "editor.active_wrap_guide": "${foreground}",
	        "editor.document_highlight.read_background": "${color2}29",
	        "editor.document_highlight.write_background": "${color2}29",
			"editor.indent_guide_active": "${foreground}26",
			"editor.indent_guide": "${foreground}08",
	        "terminal.background": "${background}4D",
	        "terminal.foreground": "${foreground}",
	        "terminal.dim_foreground": "${foreground}B3",
	        "terminal.bright_foreground": "${color7}",
	        "terminal.ansi.black": "${eblack}",
	        "terminal.ansi.red": "${ered}",
	        "terminal.ansi.green": "${egreen}",
	        "terminal.ansi.yellow": "${elyellow}",
	        "terminal.ansi.blue": "${eblue}",
	        "terminal.ansi.magenta": "${emagenta}",
	        "terminal.ansi.cyan": "${ecyan}",
	        "terminal.ansi.white": "${ewhite}",
	        "terminal.ansi.bright_black": "${elblack}",
	        "terminal.ansi.bright_red": "${elred}",
	        "terminal.ansi.bright_green": "${elgreen}",
	        "terminal.ansi.bright_yellow": "${elyellow}",
	        "terminal.ansi.bright_blue": "${elblue}",
	        "terminal.ansi.bright_magenta": "${elmagenta}",
	        "terminal.ansi.bright_cyan": "${elcyan}",
	        "terminal.ansi.bright_white": "${elwhite}",
	        "terminal.ansi.dim_black": "#45475a",
	        "terminal.ansi.dim_red": "#f38ba8",
	        "terminal.ansi.dim_green": "#a6e3a1",
	        "terminal.ansi.dim_yellow": "#f9e2af",
	        "terminal.ansi.dim_blue": "#89b4fa",
	        "terminal.ansi.dim_magenta": "#f5c2e7",
	        "terminal.ansi.dim_cyan": "#94e2d5",
	        "terminal.ansi.dim_white": "#bac2de",
	        "link_text.hover": "#89dceb",
	        "conflict": "#cba6f7",
	        "conflict.border": "#cba6f7",
	        "conflict.background": "#181825",
	        "created": "${color10}",
	        "created.border": "${color10}",
	        "created.background": "${background}",
	        "deleted": "${altforeground}",
	        "deleted.border": "${altforeground}",
	        "deleted.background": "${background}",
	        "error": "${color1}",
	        "error.border": "${color1}",
	        "error.background": "${background}",
	        "hidden": "${altforeground}",
	        "hidden.border": "${altforeground}",
	        "hidden.background": "${background}",
	        "hint": "#FFFFFF",
	        "hint.border": "#585b70",
	        "hint.background": "${background}",
	        "ignored": "${altforeground}",
	        "ignored.border": "${altforeground}",
	        "ignored.background": "${background}",
	        "info": "${color4}",
	        "info.border": "${color4}",
	        "info.background": "${modbackground[1]}66",
	        "modified": "${color5}",
	        "modified.border": "${color5}",
	        "modified.background": "${background}",
	        "predictive": "${color4}",
	        "predictive.border": "${color4}",
	        "predictive.background": "${background}",
	        "renamed": "${color6}",
	        "renamed.border": "${color6}",
	        "renamed.background": "${background}",
	        "success": "${color9}",
	        "success.border": "${color9}",
	        "success.background": "${background}",
	        "unreachable": "${color1}",
	        "unreachable.border": "${color1}",
	        "unreachable.background": "${background}",
	        "warning": "${color3}",
	        "warning.border": "${color3}",
	        "warning.background": "${background}",
	        "players": [
	          {
	            "cursor": "#f5e0dc",
	            "selection": "#FFFFFF80",
	            "background": "#f5e0dc"
	          },
	          {
	            "cursor": "#a9d0f0",
	            "selection": "#a9d0f033",
	            "background": "#a9d0f0"
	          },
	          {
	            "cursor": "${foreground}",
	            "selection": "${foreground}33",
	            "background": "${foreground}"
	          },
	          {
	            "cursor": "#b6dae7",
	            "selection": "#b6dae733",
	            "background": "#b6dae7"
	          },
	          {
	            "cursor": "#dfc8c8",
	            "selection": "#dfc8c833",
	            "background": "#dfc8c8"
	          },
	          {
	            "cursor": "#dfdad8",
	            "selection": "#dfdad833",
	            "background": "#dfdad8"
	          },
	          {
	            "cursor": "#b2c8f6",
	            "selection": "#b2c8f633",
	            "background": "#b2c8f6"
	          },
	          {
	            "cursor": "#bddbd2",
	            "selection": "#bddbd233",
	            "background": "#bddbd2"
	          }
	        ],
	        "syntax": {
	          "attribute": {
	            "color": "${eblue}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "boolean": {
	            "color": "${ecyan}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "comment": {
	            "color": "${ecomment}",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "comment.doc": {
	            "color": "${ecomment}",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "constant": {
	            "color": "${eblue}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "constructor": {
	            "color": "${eyellow}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "embedded": {
	            "color": "${eyellow}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "emphasis": {
	            "color": "${eyellow}",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "emphasis.strong": {
	            "color": "${eyellow}",
	            "font_style": null,
	            "font_weight": 700
	          },
	          "enum": {
	            "color": "${eblue}",
	            "font_style": null,
	            "font_weight": 700
	          },
	          "function": {
	            "colorp": "${eblue}",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "hint": {
	            "color": "${eyellow}",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "keyword": {
	            "color": "${emagenta}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "link_text": {
	            "color": "${elblue}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "link_uri": {
	            "color": "${eyellow}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "number": {
	            "color": "${elblue}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "operator": {
	            "color": "${eyellow}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "predictive": {
	            "color": "${eyellow}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "predoc": {
	            "color": "${ecomment}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "primary": {
	            "color": "${eblue}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "property": {
	            "color": "${eblue}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation": {
	            "color": "${egreen}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.bracket": {
	            "color": "${ewhite}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.delimiter": {
	            "color": "${ecomment}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.list_marker": {
	            "color": "${ecomment}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.special": {
	            "color": "${ecomment}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "punctuation.special.symbol": {
	            "color": "${ecomment}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string": {
	            "color": "${elgreen}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.escape": {
	            "color": "${egreen}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.regex": {
	            "color": "${egreen}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.special": {
	            "color": "${egreen}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "string.special.symbol": {
	            "color": "${egreen}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "tag": {
	            "color": "${ewhite}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "text.literal": {
	            "color": "${ewhite}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "title": {
	            "color": "${ewhite}",
	            "font_style": null,
	            "font_weight": 800
	          },
	          "type": {
	            "color": "${ecyan}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "type.interface": {
	            "color": "${ecyan}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "type.super": {
	            "color": "${elcyan}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable": {
	            "color": "${eyellow}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable.member": {
	            "color": "${eyellow}",
	            "font_style": null,
	            "font_weight": null
	          },
	          "variable.parameter": {
	            "color": "${elyellow}",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "variable.special": {
	            "color": "${elred}",
	            "font_style": "italic",
	            "font_weight": null
	          },
	          "variant": {
	            "color": "${ered}",
	            "font_style": null,
	            "font_weight": null
	          }
	        }
	      }
	    }
	  ]
	}

	EOF
