## Colors configuration
[colors.primary]
background = "#090b06"
foreground = "#dcd3a6"

[colors.normal]
black   = "#090b06"
red     = "#64693A"
green   = "#555D48"
yellow  = "#6F6F4C"
blue    = "#877853"
magenta = "#7C824B"
cyan    = "#969256"
white   = "#dcd3a6"

[colors.bright]
black   = "#9a9374"
red     = "#64693A"
green   = "#555D48"
yellow  = "#6F6F4C"
blue    = "#877853"
magenta = "#7C824B"
cyan    = "#969256"
white   = "#dcd3a6"
