## Colors configuration
[colors.primary]
background = "#03142C"
foreground = "#d8d2ce"

[colors.normal]
black   = "#060f21"
red     = "#f68c57"
green   = "#2d7269"
yellow  = "#979777"
blue    = "#4374c3"
magenta = "#9a91c8"
cyan    = "#4dd2d9"
white   = "#e4dfdc"

[colors.bright]
black   = "#878685"
red     = "#ffb294"
green   = "#429c9a"
yellow  = "#bebe96"
blue    = "#6893e4"
magenta = "#c6a9e0"
cyan    = "#8ce5ea"
white   = "#ffffff"
