## Colors configuration
[colors.primary]
background = "#041516"
foreground = "#c5f1db"

[colors.normal]
black   = "#031011"
red     = "#948771"
green   = "#4f9a75"
yellow  = "#9ce499"
blue    = "#9482bb"
magenta = "#cab5bd"
cyan    = "#c2f2c4"
white   = "#d7f5e6"

[colors.bright]
black   = "#848f8a"
red     = "#b5b69f"
green   = "#7cb38f"
yellow  = "#c8f0ae"
blue    = "#b7a0e3"
magenta = "#f7c5f0"
cyan    = "#d3fffe"
white   = "#ffffff"
