set -g default-terminal "screen-256color"
set -ga terminal-overrides ",xterm-256color*:Tc"
set -as terminal-features ",xterm-256color:RGB"

set-option -g default-shell ${SHELL}

unbind C-b

# General
set -g prefix M-Space
bind-key M-Space send-prefix
bind r source-file ~/.config/tmux.conf \; display-message "#[fg=#c0af68] RELOADING CONFIGURATION FILE…"

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g status-position top
set-option -g set-titles on
set-option -g renumber-windows on

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# Keyboard
# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# Use Alt-arrow keys without prefix key to switch panes
bind -n M-l select-pane -L
bind -n M-h select-pane -R
bind -n M-k select-pane -U
bind -n M-j select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Shift Alt vim keys to switch windows
# bind -n M-H previous-window
# bind -n M-L next-window

bind -n M-t new-window -c "#{pane_current_path}"

bind v split-window -h -c "#{pane_current_path}"
bind h split-window -v -c "#{pane_current_path}"


# Theme
set -g status "on"
set -g status-justify "left"
set -g status-style "bg=black,fg=black"
set -g status-left-style "none"
set -g status-left-length "100"
set -g status-right-style "bg=#414868"
set -g status-right-length "120"

set -g pane-border-style "fg=#24283b"
set -g pane-active-border-style "fg=#414868"

set -g message-style "bg=black,fg=white"

set -g status-right "#[bg=#9ece6a, fg=black, bold]#{?#{client_prefix}, *PREFIX ACTIVE* #[bg=black] ,}#[bg=#7aa2f7, fg=#24283b, nobold] #([ \"$(pwd)\" == $HOME ] && echo \"\" || (echo \"\")) #([ \"$(pwd)\" == $HOME ] && echo \"$USER\" || pwd | awk \'{print A[split($1,A,\"/\")]}\') #[bg=#7dcfff, fg=#24283b] %a, %b %d | %H:%M "
set -g status-left " " 

set -g window-status-separator " "

set -g window-status-format "#[bg=#414868, fg=#cfc9c2] #I #[bg=#343b58, fg=#cfc9c2] 󰓩 #W "
set -g window-status-current-format "#[bg=#bb9af7,fg=#15161E] #I #[bg=#414868, fg=#cfc9c2] 󰓩 #W "

# Run Plugins
run-shell ~/.tmux/plugins/tmux-sensible/sensible.tmux
run-shell ~/.tmux/plugins/tmux-fzf/main.tmux
run-shell ~/.tmux/plugins/tmux-menus/menus.tmux
run-shell ~/.tmux/plugins/tmux-sessionist/sessionist.tmux
