#!/usr/bin/env bash

# Source Theme file
DIR="$HOME/.config/varix"
source "$DIR"/theming/current.bash

# Colors
bg=${background:1}  fg=${foreground:1}
red=${color1:1}     green=${color2:1}    yellow=${color3:1}
blue=${color4:1}    magenta=${color5:1}  cyan=${color6:1}
alpha='00000000'

# CMD
swaylock -f \
	\
	`# General` \
	--ignore-empty-password \
	--show-failed-attempts \
	--hide-keyboard-layout \
	--indicator-caps-lock \
	\
	`# Appearance` \
	--color ${bg}E6 \
	--font 'Cabin' --font-size 22 \
	\
	`# Backspace Key` \
	--key-hl-color ${green} \
	--caps-lock-key-hl-color ${blue} \
	--bs-hl-color ${red} \
	--caps-lock-bs-hl-color ${red} \
	\
	`# Indicator` \
	--indicator \
	--indicator-radius 160 \
	--indicator-thickness 12 \
	\
	`# Inside Circle Colors` \
	--inside-color ${alpha} \
	--inside-clear-color ${alpha} \
	--inside-caps-lock-color ${alpha} \
	--inside-ver-color ${blue} \
	--inside-wrong-color ${red} \
	\
	`# Layout Colors` \
	--layout-bg-color ${cyan} \
	--layout-border-color ${cyan} \
	--layout-text-color ${bg} \
	\
	`# Line Colors` \
	--line-color ${bg} \
	--line-clear-color ${red} \
	--line-caps-lock-color ${bg} \
	--line-ver-color ${bg} \
	--line-wrong-color ${bg} \
	\
	`# Ring Colors` \
	--ring-color ${cyan} \
	--ring-clear-color ${bg} \
	--ring-caps-lock-color ${magenta} \
	--ring-ver-color ${blue} \
	--ring-wrong-color ${red} \
	\
	`# Separator Color` \
	--separator-color ${bg} \
	\
	`# Text Colors` \
	--text-color ${fg} \
	--text-clear-color ${fg} \
	--text-caps-lock-color ${fg} \
	--text-ver-color ${bg} \
	--text-wrong-color ${bg} \
	--screenshots \
		--clock \
		--effect-blur 7x5 \
		--effect-vignette 0.5:0.5 \
		--grace 2 \
		--fade-in 0.2
