#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>

# Import Current Theme
RASI="/home/aaron/.config/rofi/windows.rasi"

# Run
rofi \
    -show window \
    -window-thumbnail \
	-theme ${RASI}
