#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Set Wallpaper in Hyprland

# Get the current wallpaper path from the current.bash file
source /home/aaron/.config/varix/theming/current.bash
WALLPAPER="$wallpaper"

swaybg --output '*' --mode stretch --image "$WALLPAPER"
