#!/usr/bin/env bash

WHO=$1  # workspace number

# Check if $1 is not empty and is a number
if [[ -n $WHO && $WHO =~ ^[0-9]+$ ]]; then
    # The first one starts the 'server'
    if [ "${WHO}" -eq "1" ]; then
        ~/.config/varix/scripts/ws_labwc & 
    fi

    # Rest of your script handling the WHO variable
    SYMBOLS=(1 2 3 4 5 6 7 8 9)
    CLASSES=("inactive" "active")
    FIFO="/tmp/waybar.ws${WHO}-module"

    if [ ! -p "${FIFO}" ]; then
        mkfifo "${FIFO}"
    fi

    # Initial state
    if [ "${WHO}" -eq "1" ]; then
        echo "{\"text\": \"${SYMBOLS[((WHO-1))]}\", \"class\": \"${CLASSES[1]}\"}"
    else
        echo "{\"text\": \"${SYMBOLS[((WHO-1))]}\", \"class\": \"${CLASSES[0]}\"}"
    fi

    while read line <$FIFO; do
        echo "{\"text\": \"${SYMBOLS[((WHO-1))]}\", \"class\": \"${CLASSES[$line]}\"}"
    done
else
    echo "Invalid workspace number. Please provide a valid integer."
    exit 0
fi
